# Generated by Django 5.2 on 2025-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleprogress',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
