# Generated by Django 5.2 on 2025-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_achievement_usermoduleprogress_time_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleprogress',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
