# Generated by Django 5.2 on 2025-04-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_usermoduleprogress_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleprogress',
            name='time_spent',
            field=models.IntegerField(default=100),
        ),
    ]
